[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "build"  # Changed from "public" to "build" since that's where your assets are

[functions]
  node_bundler = "esbuild"
  included_files = ["build/**"]

[[redirects]]
  from = "/assets/*"  # Simplified this path
  to = "/client/assets/:splat"
  status = 200

[[headers]]
  for = "/assets/*"  # Updated to match your asset path
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, immutable"